### ISSUE TITLE
Add ability to change touch sensitivity for Device Simulator / Game View

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/ar-simulation#22]
**What workflow / functionality is missing?**
When Device Simulator is used in portrait mode mouse events are only simulated as touch events when inside the device view (which _kind of_ makes sense).
However, that leads to pretty slow movement (not much mouse space to move).
(probably also an issue that fast mouse movements currently counter-intuitively result in less camera motion)

![200615-154316](https://user-images.githubusercontent.com/2693840/84664527-f440f980-af1e-11ea-9523-ce408d233b0c.gif)

**Describe the solution you'd like**
Either allow touch simulation everywhere on the window
Or add a global setting for "sensitivity"

**Describe alternatives you've considered**
Sensitivity can currently be adjusted on `ARCamera/DesktopPoseProvider` however I don't want to add that component to stay flexible.

**Comment by marwie** [comment]
Fixed in next version (1.0.0-preview.6)

#### Regarding configuration:
Added global settings to ``ARSimulationLoaderSettings`` for movement and rotation sensitivity (will be automatically created by XR Plug-in Management in XR/Settings + can be found under ``Project Settings/XR-Plug-in Management/AR Simulation``)

![image](https://user-images.githubusercontent.com/5083203/85275866-3fa85a00-b481-11ea-9f00-96bd267a6be6.png)

#### Regarding fast movements:
Fixed issue with clamped mouse delta to a way too low value. Movement should feel now much better and direct.
