### ISSUE TITLE
Switching from Game View to Device Simulator after pressing play breaks movement simulation

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/ar-simulation#24]
**Describe the bug**

Switching from Game View to Device Simulator after pressing play breaks movement simulation, even after switching back to GameView. Left click continues to work but drag not (neither LMB nor RMB).

**Assumption**: somehow when switching windows a simulated touch gets into a wrong state.
Sometimes after randomly clicking around and dragging with left mouse, movement starts working again.

**Steps to reproduce the behavior**
1. Open scene 'XRInteractionToolkit/AR/ARInteraction'
3. Switch to GameView
3. Press play
4. Move around
5. Switch to DeviceSim
5. Try to move around
5. Switch back to GameView
5. Try to move around

**Expected behavior**

Movement works

**Actual behavior**

Movement stops working after initial switch and stays broken afterwards

**Screenshots / GIFs**

![20200617-013801](https://user-images.githubusercontent.com/2693840/84838650-3b241180-b03b-11ea-96cf-d36faddd521a.gif)

**Versions (please complete the following information):**
 - Unity 2019.3.15f1
 - ARFoundation 3.0.3
 - OS: Windows
 - ARSimulation 1.0.0-preview.4

**Comment by marwie** [comment]
Findings so far:
does not work in Device Simulator 2.2.1-preview (the version XR Interaction toolkit has currently installed)
when upgrading to Device Simulator 2.2.2-preview switching works just fine

**Comment by marwie** [comment]
It looks like when using device simulator prior to 2.2.2-preview we only receive a left mouse down and mouse drag event but never mouse up so left mouse button gets stuck. This does not hoppen in Device Simulator 2.2.2-preview.

In the current version right mouse pressed state is only active if left button is **not**! 
The reason for this is when simulating touches we receive **both left and right** mouse button events, so when trying to left click and drag (with Simulate Touch being enabled) we ALSO rotate the camera - a behaviour we want to avoid.

Due to this movement breaks when left button events get stuck at "pressed=true".

To fix this for older device simulator versions I added a compiler directive for older Device Simulator versions to allow right mouse buttons being pressed even if left button is in pressed state.
