### ISSUE TITLE
AR Foundation - AR Session button links are lost when scene is reloaded in editor

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/ar-simulation#27]
**Describe the bug**

Reloading   the scene in editor breaks links to the AR Session on buttons - not sure if   this is a glitch from AR Foundation samples not being ready for editor   simulation?

**Steps to reproduce the behavior**

1.Using   arfoundation samples - open Scenes > SimpleAR> SimpleAR
2. Setup ARSimulation for the project and hit play 
3. Use the 'reload' button in the scene, see all other button links break   after that.

**Expected behavior**

Scene should work exactly the same when reloaded in editor play mode

**Actual behavior**

Button links to the AR Session component get lost somehow!

**Screenshots / GIFs**

[Video](https://drive.google.com/file/d/1Jttjdrssp-nHlMVlw4IX2Coia6wD6csL/view?usp=sharing) 

**Versions (please complete the following information):**
- Unity [2020.2.0a13]
- ARFoundation [e.g. 4.0]
- OS: [Windows 10]
- ARSimulation [e.g. 1.0.0 - preview 4]

**Comment by marwie** [comment]
Looking at the code they instantiate a new session and events should be reassigned but the inspector displays event listeners as "missing". Maybe it's a visual glitch? I'll try to see if buttons are actually broken in builds as well...

**Comment by ROBYER1** [comment]
Reload and reset buttons appeared to not work, do check all 4 buttons in that scene. Not sure why it happens!

**Comment by marwie** [comment]
Hi Robert, I tried all the buttons :) 
They appear to work for me even after reloading, but the event inspector shows a "missing reference" which seems not be true because clicking the buttons still seems to work as before. 

[Here is a video to verify](https://drive.google.com/file/d/1_dR8pBTUVtDpnhFWy5MxEi3Q5w-LdJFl/view?usp=sharing). I'm not 100% sure if this is a new Unity bug because I never added event listeners via scripts like that to Unity Events :)
