### ISSUE TITLE
Camera movement and AR object interaction not working on Linux

### ISSUE THREAD

**Issue by Lyot** [needle-tools/ar-simulation#44]
**Describe the bug**
Before buying your asset I wanted to test it using the package here on Github (I really like it so far btw 👍).

However, I ran into a problem on my Linux system. Basically, all camera movement and interaction with AR objects is not reacting to input. UI elements and detection of point clouds/planes are working as expected.

I tried this with all three input systems (old, new and both).

**Steps to reproduce the behavior**
1. Open any sample scene from `ar-simulation` or the `arfoundation-samples` repository
2. Press play
3. Try to move by holding `RMB` + `WASD` keys
4. Try to click on a detected plane to spawn an object
4. Nothing happens

**Expected behavior**
- Being able to move around while holding `RMB` + `WASD` keys
- Being able to interact with AR objects, e.g. spawning objects on a detected plane and moving them around

**Actual behavior**
- Nothing happens, no error is logged

**Probable Cause/Fix**
What got it working for me was changing

```cs
#if !UNITY_EDITOR_OSX
```

to

```cs
#if !UNITY_EDITOR_OSX && !UNITY_EDITOR_LINUX
```

in `Runtime/Compatibility/InputHelper.cs` on line 257.
Not quite sure why, but `Event.current.pointerType` returns some integer such as `364674904` instead of the expected `PointerType.Mouse` enumeration.

**Versions:**
 - Unity 2020.2.0f1
 - ARFoundation 4.1.1
 - OS: Linux (OpenSUSE Tumbleweed 20201221)
 - ARSimulation 1.0.5
 - no relevant packages

I also got a somewhat unrelated question.
Somewhere I read that meshing simulation is only supported for Windows and OSX (the former I can confirm). Is this true? Because on my system nothing happens when I run the provided *Meshing Example* sample. Just want to make sure that it actually is an issue before looking into it.

**Comment by marwie** [comment]
Hello @Lyot 

thanks for the good report. I have to admit that we haven't tested on Linux properly yet, but it looks like we have forgotten to include the platform in the #ifdefs. I'll just go ahead and try to fix those. 

About ``pointerType`` that sounds like an issue with Unity, but I would have to investigate on Linux first. If we're not able to find out if ``pointerType`` is a mouse we have a problem.

About meshing: It's only supported/tested on windows and mac so far, yes, so if nothing happens that is expected because we haven't built the plugin for Linux yet. Would you need Meshing support for your projects?

Do you have [![Discord Link]](https://discord.gg/CFZDp4b) or an email? I could send you a pre-release version to try once I've added some fixes.

Cheers
Marcel

**Comment by Lyot** [comment]
Hello @marwie 

thanks for the quick response.

Since the fix it works as expected.

And yes, support for Meshing would be really helpful as it is quite important for my current project.
A hotfix would be great, thank you. I'll contact you in Discord.

Greetings
Jonathan
